from enum import StrEnum

class AuditActionEnum(StrEnum):

    # CRUD Audit
    CREATE = "CREATE"
    READ = "READ"
    UPDATE = "UPDATE"
    DELETE = "DELETE"

    # Authentication Audit
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    LOGIN_FALED = "LOGIN_FAILED"

    # Account
    REGISTER = "REGISTER"
    PASSWORD_CHANGE = "PASSWORD_CHANGE"
    PASSWORD_RESET = "PASSWORD_RESET"
    EMAIL_VERIFICATION = "EMAIL_VERIFICATION"
    RESEND_EMAIL_VERIFICATION = "RESEND_EMAIL_VERIFICATION"
    FORGOT_PASSWORD = "FORGOT_PASSWORD"