# Generated by Django 6.0.7 on 2026-09-18 04:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_public_id', models.CharField(blank=True, max_length=500, null=True)),
                ('profile_name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('profile_content_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
