# Generated by Django 6.0.7 on 2026-08-10 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_filename',
        ),
    ]
