# Generated by Django 6.0.7 on 2026-09-18 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'account_type': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchantinvitation',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='merchants.merchant'),
        ),
        migrations.AddField(
            model_name='merchantstaff',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='merchants.merchant'),
        ),
        migrations.AddField(
            model_name='merchantstaff',
            name='user',
            field=models.ForeignKey(limit_choices_to={'account_type': 'staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_employments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='merchantstaff',
            constraint=models.UniqueConstraint(fields=('merchant', 'user'), name='unique_merchant_staff'),
        ),
    ]
