# Generated by Django 6.0.7 on 2026-09-01 07:16

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='user',
        ),
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_business', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='businessmember',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='business.business'),
        ),
        migrations.AlterField(
            model_name='businessmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Business Owner'), ('cashier', 'Cashier'), ('manager', 'Manager')], max_length=20),
        ),
        migrations.AlterField(
            model_name='businessmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='businessmember',
            constraint=models.UniqueConstraint(fields=('business', 'user'), name='unique_business_member'),
        ),
    ]
