# Generated by Django 6.0.7 on 2026-09-18 04:42

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('food', 'Food'), ('beverages', 'Beverages'), ('electronics', 'Electronics'), ('office', 'Office'), ('services', 'Services')])),
                ('payment_terms', models.CharField(choices=[('cash', 'Cash'), ('cod', 'Cash on Delivery'), ('net 7', 'Net 7'), ('net 15', 'Net 15'), ('net 30', 'Net 30'), ('net 60', 'Net 60')], max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('is_active', models.BooleanField(default=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='merchants.merchant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('merchant', 'company_name'), name='unique_supplier_company_per_merchant'), models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('merchant', 'email'), name='unique_supplier_email_per_merchant')],
            },
        ),
    ]
