# Generated by Django 6.0.7 on 2026-08-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
