# Generated by Django 6.0.7 on 2026-09-18 04:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(editable=False, max_length=20, null=True, unique=True)),
                ('supplier_name', models.CharField(max_length=100)),
                ('items', models.JSONField(default=list)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_terms', models.CharField(choices=[('cash', 'Cash'), ('cod', 'Cash on Delivery'), ('net 7', 'Net 7'), ('net 15', 'Net 15'), ('net 30', 'Net 30'), ('net 60', 'Net 60')])),
                ('status', models.CharField(choices=[('in transit', 'In Transit'), ('pending', 'Pending'), ('delivered', 'Delivered')], null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='merchants.merchant')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='purchase_order_total_amount_gte_zero'), models.UniqueConstraint(fields=('merchant', 'po_number'), name='unique_merchant_po_number')],
            },
        ),
    ]
