# Generated by Django 6.0.7 on 2026-09-17 05:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted'), ('LOGIN', 'Login'), ('LOGIN FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('REGISTER', 'Register'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset'), ('EMAIL_VERIFICATION', 'Email Verification'), ('RESEND_EMAIL_VERIFICATION', 'Resend Email Verification'), ('FORGOT_PASSWORD', 'Forgot Password')], max_length=50)),
                ('module_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('original', models.JSONField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ('-created_at',),
            },
        ),
    ]
