# Generated by Django 6.0.7 on 2026-08-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logging', '0002_remove_auditlog_status_auditlog_user_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted'), ('LOGIN', 'Login'), ('LOGIN FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('REGISTER', 'Register'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset'), ('EMAIL_VERIFICATION', 'Email Verification'), ('RESEND_EMAIL_VERIFICATION', 'Resend Email Verification'), ('FORGOT_PASSWORD', 'Forgot Password')], max_length=50),
        ),
    ]
