# Generated by Django 6.0.7 on 2026-09-18 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='merchants.merchant'),
        ),
        migrations.AddField(
            model_name='branchmember',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='branchmember',
            name='merchant_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_members', to='merchants.merchantstaff'),
        ),
        migrations.AddConstraint(
            model_name='branchmember',
            constraint=models.UniqueConstraint(fields=('branch', 'merchant_member'), name='unique_branch_member'),
        ),
    ]
