# Generated by Django 6.0.7 on 2026-09-18 04:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('beverages', 'Beverages'), ('dairy', 'Dairy'), ('bakery', 'Bakery'), ('packaging', 'Packaging'), ('general', 'General')])),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(max_length=50)),
                ('product_image_public_id', models.CharField(max_length=255)),
                ('retail_selling_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('cogs', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_quantity', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('low_stock_threshold', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_status', models.CharField(choices=[('in stock', 'In Stock'), ('low stock', 'Low Stock'), ('out of stock', 'Out of Stock')], default='in stock')),
                ('reason', models.TextField(blank=True, max_length=255, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='merchants.merchant')),
                ('suppliers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='suppliers.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
